### PR TITLE
upload of FFT spectrogram on the node-red ui heatmap

### PR DESCRIPTION
**Pull request by cmayor314**
For this image, I used the dashboard ui heatmap to create a frequency spectrogram
with 75 harmonics, and 150 time samples.  
The Fast Fourier Transform (FFT) nodejs library, fft-s, performs the calculations.
The source of the FFT frequencies is water depth time samples.

I release this image into the public domain.

### CODE REVIEW

**Comment by bartbutenaers** [comment]
Hi @cmayor314,
Thanks for sharing this nice and original use case for heatmaps!
I have added it to the readme page.
Kind regards,
Bart

**Comment by cmayor314** [comment]
Hi Bart,

I didn't see any use-case images for heatmaps that looked like my spectrogram, so I was happy to submit it as another example for people.  Thanks for writing the node-red heatmap

cheers,
Cam

**Comment by cmayor314** [comment]
Oh, sorry to bother you, it looks like I had a typo in my description.   It was the fft-js library, not the fft-s library.  Sorry for the mixup

https://www.npmjs.com/package/fft-js

**Comment by bartbutenaers** [comment]
Oh no problem.  I should have checked it myself. It is now fixed on the readme, and the link to npm is added.

**Pull request merged**
